version: '3.8'
services:
  react-app:
    build: .
    container_name: pixel-advant
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
